#### Configuration
DEBUG: False
batch_size: 1
num_workers: 8
pin_memory: True
train_shuffle: True
val_shuffle: False
validation_split: 0.2
shuffle_dataset_split: True
random_seed_split: 42

# PATHS
train_path: ../data/knnw_en.log_spectrogram.npy
train_labels: ../data/knnw_en_sub.csv
# val_path: /home/gman/785/hw2p2/data/val_data/
# test_path: /home/gman/785/hw2p2/data/test_data/
# verify_path: /home/gman/785/hw2p2/data/verification_data/
# classify_out_path: /home/gman/785/hw2p2/results/classify/
# verify_out_path: /home/gman/785/hw2p2/results/verify/
# ray_results_dir: /home/gman/785/hw2p2/ray_results/
# checkpoints_path: /home/gman/785/hw2p2/checkpoints/